workflows:
  ios-build:
    name: IOS Build
    environment:
      xcode: latest
      node: latest
    scripts:
      - npm install
      - cd ios
      - pod install
      - cd ..
      - npx react-native bundle \
        --entry-file index.js \
        --platform ios \
        --dev false \
        --bundle-output ios/main.jsbundle \
    artifacts:
      - ios/build/**/*.ipa
